# Generated by Django 3.2.7 on 2022-06-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0004_alter_hotels_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
