# Generated by Django 3.2.7 on 2022-06-11 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0007_rename_messages_contactus_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 11, 20, 46, 4, 705345)),
        ),
    ]
