# Generated by Django 3.2.7 on 2022-06-17 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0009_alter_contactus_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=500)),
                ('checkInCheckOut', models.CharField(max_length=500)),
                ('rooms', models.IntegerField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 17, 21, 21, 49, 308810))),
            ],
        ),
        migrations.AlterField(
            model_name='contactus',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 17, 21, 21, 49, 308810)),
        ),
    ]
