# Generated by Django 3.2.7 on 2022-06-17 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0011_auto_20220617_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 17, 21, 32, 25, 678)),
        ),
        migrations.AlterField(
            model_name='search',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 17, 21, 32, 25, 1678)),
        ),
    ]
