# Generated by Django 3.2.7 on 2022-06-18 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0014_auto_20220617_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 18, 18, 54, 8, 611087)),
        ),
        migrations.AlterField(
            model_name='search',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 18, 18, 54, 8, 612087)),
        ),
    ]
