# Generated by Django 3.2.7 on 2022-06-19 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0015_auto_20220618_1854'),
        ('Hotels', '0015_rename_iframe_hotels_maplink_alter_contactus_date_and_more'),
    ]

    operations = [
    ]
